name: Python Tests

on: [push, pull_request]

jobs:
  python_test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: login_teste
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest coverage pytest-html

      - name: Wait Postgres start
        run: sleep 10

      - name: Run tests with coverage and generate reports
        run: |
          coverage run -m pytest --html=reports/test_report.html --self-contained-html
          coverage xml -o reports/coverage.xml
          coverage html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/test_report.html

      - name: Upload coverage report (XML and HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            reports/coverage.xml
            htmlcov/
      
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Run Flutter tests
        run: flutter test
